name: Deploy

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy en servidor
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: 187.77.245.74
          username: root
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd /tmp/bot-deploy
            git pull origin main
            docker build --no-cache -t bicicleteria_bot-bicicleteria:latest .
            docker service update --force --image bicicleteria_bot-bicicleteria:latest bicicleteria_bot-bicicleteria
            echo "✅ Deploy completado"
